// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9bXPuiKkHaTmntp9rpsIPM5s0EoFyaOs',
    appId: '1:790766635338:web:b510f1f91c4d6eabe159b3',
    messagingSenderId: '790766635338',
    projectId: 'smartpaydevicemanagement-5d26b',
    authDomain: 'smartpaydevicemanagement-5d26b.firebaseapp.com',
    storageBucket: 'smartpaydevicemanagement-5d26b.firebasestorage.app',
    measurementId: 'G-T50SPJQER6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcs14YLyNlQXU_vdThSiL4Zl6uay_j-N4',
    appId: '1:790766635338:android:47672345913b7dfde159b3',
    messagingSenderId: '790766635338',
    projectId: 'smartpaydevicemanagement-5d26b',
    storageBucket: 'smartpaydevicemanagement-5d26b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnWh-qre3cFsilzWmFwVG1Fn-tzjhPTu8',
    appId: '1:790766635338:ios:637af31d1fe58308e159b3',
    messagingSenderId: '790766635338',
    projectId: 'smartpaydevicemanagement-5d26b',
    storageBucket: 'smartpaydevicemanagement-5d26b.firebasestorage.app',
    iosBundleId: 'com.example.devicelocunlock',
  );
}
